#!/bin/bash
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyBaselin[^"]*|https://photos.app.goo.gl/6yEDT7QCcEoHM6uF6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyBlacherov[^"]*|https://photos.app.goo.gl/Z3AJy3eaCm5ZnpSg7|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/FamilyBobrik[^"]*|https://photos.app.goo.gl/wvLXQGJYfqBYEE6A8|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/ChaitErukhimovichFamily[^"]*|https://photos.app.goo.gl/CvyZvhiSwsA8YyGp6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/ChilkevichFamily[^"]*|https://photos.app.goo.gl/qEARvLUt3Z1QfmCw7|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/FamilyErukhimovich[^"]*|https://photos.app.goo.gl/oCQQHKaJW6EtqSkE7|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/FischelPajkinFamily[^"]*|https://photos.app.goo.gl/iZB2zLvYFSWrTuEG6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/GindinGoldinTarnogradskyLetuchijFamily[^"]*|https://photos.app.goo.gl/m18NzAtqXLGg5QRu6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/GindinGoldinFamily[^"]*|https://photos.app.goo.gl/qNZ9pnHQBw9KHN8j8|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/GoldinLesinShpirtFamily[^"]*|https://photos.app.goo.gl/v8Nh6QiGiNiHGwdK6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/GorelikFamily[^"]*|https://photos.app.goo.gl/MzLiLFyWRB3z1LHr6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/GurevichGurovichBankFamily[^"]*|https://photos.app.goo.gl/M2V98J2n5LmR5V9H8|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/Hgrqd[^"]*|https://photos.app.goo.gl/HTobpvEgV1PbNFep6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/JanowskiFamily[^"]*|https://photos.app.goo.gl/TUf4UiFxoMfz1kNx7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyKadaner[^"]*|https://photos.app.goo.gl/gLNUwFZcMZkR5f8J7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/KovadloFamily[^"]*|https://photos.app.goo.gl/RZr8HBsR6X8Shjzf7|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/FamilyKuklinsky[^"]*|https://photos.app.goo.gl/gdVRaW3TJQHEK6GQ7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/KuklinskyBaskinFamily[^"]*|https://photos.app.goo.gl/SRUjmZkMBZ5PEKB97|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/KuklinskyMetznerFamily[^"]*|https://photos.app.goo.gl/xDJU43jw3BWkGhNBA|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/LangFamily[^"]*|https://photos.app.goo.gl/a2H3oMuJTRAm5K9Q6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyLavyt[^"]*|https://photos.app.goo.gl/TXLqNQ7Zb1TA4rWz9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/FamilyLevin[^"]*|https://photos.app.goo.gl/TrETJfBWjEFyEW8c9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/IzFotoalbomaMLevitaINKuklinskoj[^"]*|https://photos.app.goo.gl/qNaCzEShH5g5cV1u6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/MakhlinFamily[^"]*|https://photos.app.goo.gl/AkAmpxHy8JXkTTpG9|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/MalinskiFamily[^"]*|https://photos.app.goo.gl/BL62TsmikSFR8FLM8|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyMaryash[^"]*|https://photos.app.goo.gl/eiLWSXzfYi3nMGGdA|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/MeerovitchFamily[^"]*|https://photos.app.goo.gl/Pq1LcR7Xhfq9EHrB6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/MeznerFamily[^"]*|https://photos.app.goo.gl/2R7vqQv7G4j9g3Km9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/MeznerGoldinFamily[^"]*|https://photos.app.goo.gl/QA6eSZC7Rho5mySRA|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyMuravankin[^"]*|https://photos.app.goo.gl/7oBxMNSPSxQUjVVf7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyNahumTsodikovichKuklinsky[^"]*|https://photos.app.goo.gl/8KtVvB8EhKSWQvkX9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/spcnqC[^"]*|https://photos.app.goo.gl/eMUHQ6jxC5Rx9nns6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/spcnqC[^"]*|https://photos.app.goo.gl/eMUHQ6jxC5Rx9nns6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/PilmeysterFamily[^"]*|https://photos.app.goo.gl/K1pz2qWqeSnUwC7J6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyRautshteyn[^"]*|https://photos.app.goo.gl/cN6D72KU15Y74YwH6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/SayEnH[^"]*|https://photos.app.goo.gl/PVhZdh4ynZY9CQxK6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/Romanovskie[^"]*|https://photos.app.goo.gl/yDRcdCm71iivhQDcA|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/SchkloverFamily[^"]*|https://photos.app.goo.gl/fiqzj8QpzZm2PRj38|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/FamilyShtern[^"]*|https://photos.app.goo.gl/hm4heCd1oA23bpc79|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/CFZzJ[^"]*|https://photos.app.goo.gl/cegwFUt6rmUneTs78|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/SigelFamily[^"]*|https://photos.app.goo.gl/JNH8axZVwDhvW3hX6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/SmotkinFamily[^"]*|https://photos.app.goo.gl/CamC7HDy6wd7CW1t8|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/SoloveyFamily[^"]*|https://photos.app.goo.gl/r2eivXAZuoEcF3Jf9|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilySverdlov[^"]*|https://photos.app.goo.gl/8eDZmL7WXLUN8Vxx9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/LwEfZC[^"]*|https://photos.app.goo.gl/kKUZfKRRSZgjy8qZ9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/QYapOD[^"]*|https://photos.app.goo.gl/6BAmb9rL6k1oRe5i7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/TsirulnikovFamily[^"]*|https://photos.app.goo.gl/te6DamnrcLXHm4mn9|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/VelshteynFamily[^"]*|https://photos.app.goo.gl/jx5AZeUPJhPKLaxC9|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/VinovFamily[^"]*|https://photos.app.goo.gl/eqjh38o7Rd9pxgWH8|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/VorobievFamily[^"]*|https://photos.app.goo.gl/cKpSW6FmBdVF2kZJ9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/E[^"]*|https://photos.app.goo.gl/p3z4ySUMFH9hx5pj6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/O[^"]*|https://photos.app.goo.gl/KxA1sshGEVXB7KzGA|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/O[^"]*|https://photos.app.goo.gl/KxA1sshGEVXB7KzGA|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/MIVVJL[^"]*|https://photos.app.goo.gl/NW2XNiNw7jXWb8Gx6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/MIVVJL[^"]*|https://photos.app.goo.gl/NW2XNiNw7jXWb8Gx6|g' foto_family.html
sed -i 's|http://picasaweb\.google\.com/koloniaromanovka/RKwIHI[^"]*|https://photos.app.goo.gl/DqoPqhD5WfpqVqaE9|g' foto_family.html
sed -i 's|http://picasaweb\.google\.de/koloniaromanovka/RKwIHI[^"]*|https://photos.app.goo.gl/DqoPqhD5WfpqVqaE9|g' foto_family.html
echo "All links updated successfully!"
# Additional families found
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/GurovichPiastroFamily[^"]*|https://photos.app.goo.gl/R7YGJtpNsDN2sRDm8|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/GrinFamily[^"]*|https://photos.app.goo.gl/YJTV7TwftLDfz68B7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyShulmanTarlavsky[^"]*|https://photos.app.goo.gl/cegwFUt6rmUneTs78|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/GindinFamily[^"]*|https://photos.app.goo.gl/Xhx58JAfrzJbFDgK6|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/LopatinFamily[^"]*|https://photos.app.goo.gl/dSiFLt1Z4iLXhLzn9|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FinkelsteinFamily[^"]*|https://photos.app.goo.gl/vAeQ1Mdb5FqG2tKUA|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/RitovFamily[^"]*|https://photos.app.goo.gl/VQ6Y41xWvpSaW4sX7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyTarlavsky[^"]*|https://photos.app.goo.gl/6BAmb9rL6k1oRe5i7|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/TomchinskyFamily[^"]*|https://photos.app.goo.gl/R36qNjgPFiQWnJnDA|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/FamilyDemburg[^"]*|https://photos.app.goo.gl/ggCHjDKj4mAG8oqC9|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/DobrovitskiiFamily[^"]*|https://photos.app.goo.gl/VdM4M2hyfp2oRjEt5|g' foto_family.html
sed -i 's|https://picasaweb\.google\.com/koloniaromanovka/KlyazFamily[^"]*|https://photos.app.goo.gl/X5UkRYi5YZDdgNgq6|g' foto_family.html
echo "Additional links updated!"
